const BASE_ID = 1960401000000000000n

const createRow = (offset, data) => ({
  id: (BASE_ID + BigInt(offset)).toString(),
  version: 0,
  deleted: false,
  ...data,
})

export const createOrganizationRows = () => [
  createRow(2, {
    parentId: '0',
    organizationCode: 'HEAD_OFFICE',
    organizationName: '总公司',
    organizationType: 'HEAD_OFFICE',
    sortNo: 10,
    treeLevel: 0,
    status: 'ENABLED',
    rescueProjects: null,
  }),
  createRow(3, {
    parentId: '0',
    organizationCode: 'BJ',
    organizationName: '北京分公司',
    organizationType: 'BRANCH',
    sortNo: 20,
    treeLevel: 0,
    status: 'ENABLED',
    rescueProjects: '接电服务\n紧急送油\n更换轮胎\n拖车牵引',
  }),
  createRow(4, {
    parentId: '0',
    organizationCode: 'SH',
    organizationName: '上海分公司',
    organizationType: 'BRANCH',
    sortNo: 30,
    treeLevel: 0,
    status: 'ENABLED',
    rescueProjects: '接电服务\n现场抢修\n拖车牵引',
  }),
  createRow(5, {
    parentId: '0',
    organizationCode: 'GD',
    organizationName: '广东分公司',
    organizationType: 'BRANCH',
    sortNo: 40,
    treeLevel: 0,
    status: 'ENABLED',
    rescueProjects: '接电服务\n紧急加水\n更换轮胎\n拖车牵引',
  }),
  createRow(6, {
    parentId: '0',
    organizationCode: 'ZJ',
    organizationName: '浙江分公司',
    organizationType: 'BRANCH',
    sortNo: 50,
    treeLevel: 0,
    status: 'ENABLED',
    rescueProjects: '接电服务\n现场抢修\n拖车牵引',
  }),
  createRow(7, {
    parentId: '0',
    organizationCode: 'JS',
    organizationName: '江苏分公司',
    organizationType: 'BRANCH',
    sortNo: 60,
    treeLevel: 0,
    status: 'ENABLED',
    rescueProjects: '接电服务\n更换轮胎\n拖车牵引',
  }),
  createRow(8, {
    parentId: (BASE_ID + 3n).toString(),
    organizationCode: 'BJ_CY',
    organizationName: '北京朝阳支公司',
    organizationType: 'SUB_BRANCH',
    sortNo: 10,
    treeLevel: 1,
    status: 'DISABLED',
    rescueProjects: null,
  }),
]
